## Pytorch 에서의 Gradient Descent
    머신러닝 과정에서 살펴본 선형회귀에서 선형회귀 연산 그래프와 경사하강법을 파이토치로 구현
    파이토치에서 데이터의 기본단위는 텐서(torch.tensor())이다. Numpy에서 np.array와 같음.
    텐서를 기본단위로 연산 처리.  

In [3]:
import torch
# torchvision : Specified Library on Image Processing
import torchvision
# data augmentation
import torchvision.transforms as transforms
# Neural Network
import torch.nn as nn

import numpy as np

In [10]:
# 값 할당 안하면 무작위로 채워짐
x=torch.Tensor(2,3)
x.shape

x=torch.Tensor([[2,3,6],[3,4,5]])
x

tensor([[2., 3., 6.],
        [3., 4., 5.]])

In [11]:
'''
tensor()함수 인자값으로 data.dtype, device, requires_grad
data.dtype : 타입지정
device : 텐서를 어느 기기에 올릴지 지정(cpu,gpu)
requires_grad : 텐서의 기울기를 지정할지 여부 = 미분 사용의 여부를 묻는 것.
이거 False로 지정하면 역전파,학습 안됨
>> but 학습이 필요없는 테스트 단계에서는 False로 지정함.
'''

'\ntensor()함수 인자값으로 data.dtype, device, requires_grad\ndata.dtype : 타입지정\ndevice : 텐서를 어느 기기에 올릴지 지정(cpu,gpu)\nrequires_grad : 텐서의 기울기를 지정할지 여부 = 미분 사용의 여부를 묻는 것.\n이거 False로 지정하면 역전파,학습 안됨\n>> but 학습이 필요없는 테스트 단계에서는 False로 지정함.\n'

In [39]:
x=torch.tensor(data=[2.0,3.0],requires_grad=True)
# x=torch.tensor(data=[2.0,3.0],requires_grad=False)
x
pred=2*(x**2)+3
pred

# 1. 예측
y=torch.tensor([3.0,4.0])

# 2. 로스값 구하기
loss=torch.sum(torch.abs(pred-y))
print("loss :",loss)

# 3. 가장 큰 기울기로 하강하는 weight 찾기
# = 가장 낮은 로스값 구하는 weight 찾기...미분,편미분
loss.backward(x.grad,pred.grad)
'''
x.grad >> dy/dw =x
w.grad >> dy/dx =w
'''
print(x.grad,pred.grad)

loss : tensor(25., grad_fn=<SumBackward0>)
tensor([ 8., 12.]) None


## Tensor Type - tensor(), as_tensor()

In [54]:
'''
Pytorch의 텐서 자료형은 Numpy의 array()와 동일한 것으로 이해
'''
# 1. 리스트 만들기
li=np.array([[1,2],[3,4]])
print(li)

print("*"*60)
li_torch=torch.tensor(li)
print(li_torch,type(li_torch))

print("*"*60)
li=np.array(li_torch)
print(li,type(li))

print("*"*60)
li_torch=torch.as_tensor(li)
print(li_torch,type(li_torch))

[[1 2]
 [3 4]]
************************************************************
tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>
************************************************************
[[1 2]
 [3 4]] <class 'numpy.ndarray'>
************************************************************
tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>
