In [2]:
import numpy as np #Alising numpy as np

In [10]:
array1=np.array([2,3,5,7,11,13,17,19,23,31])
array2=np.array([[2,3,5,7],[11,13,17,19],[23,31,37,41]])

In [3]:
print(type(array1))
print(type(array2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
print(array1.shape)
print(array2.shape)
#어떤요소가 있는지 살펴보려고
#array1은 1차원 array, array2는 2차원 array

(10,)
[[ 2  3  5  7]
 [11 13 17 19]
 [23 31 37 41]]
(3, 4)


In [5]:
print(array1.size)
print(array2.size)

10
12


In [6]:
array1=np.full(8,4)
print(array1)
#np.full(a,b) : full fill array1 with b as much as a
array2=np.full(8,0)
array3=np.zeros(8,dtype=int) #when fill it with zeros, just use this code instead of above one. 
print(array2)
print(array3)
array4=np.ones(8) # same with zeros...
print(array4)

[4 4 4 4 4 4 4 4]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
#Selecting Random one Variables
array5=np.random.random(100)
print(array5)

[0.79448609 0.84824792 0.99830954 0.68758271 0.84315185 0.74069827
 0.2904992  0.97896082 0.7797155  0.73869807 0.4377108  0.7804132
 0.18172536 0.90372108 0.73916711 0.69466869 0.25995977 0.4695851
 0.44106334 0.64986663 0.64966241 0.18358926 0.40075592 0.03886287
 0.88193836 0.23989189 0.28930235 0.73186441 0.37410588 0.24142546
 0.60816265 0.84790811 0.40507236 0.39130062 0.98036662 0.00638935
 0.59755272 0.26533689 0.57413489 0.69766421 0.40156691 0.00115133
 0.04690519 0.02012803 0.41201292 0.96101821 0.48269428 0.99834357
 0.98487708 0.67070689 0.5784585  0.76503935 0.35131244 0.71967505
 0.34756777 0.87157244 0.8932933  0.12408491 0.77853738 0.30529404
 0.02536164 0.70853791 0.61481982 0.06447826 0.96441072 0.2557306
 0.09602459 0.93368001 0.82493067 0.02398967 0.75009237 0.9978684
 0.88719085 0.60022551 0.2379643  0.97291657 0.07467019 0.94851374
 0.32601983 0.92866881 0.35024121 0.39230529 0.50236709 0.11760433
 0.39617424 0.61803453 0.7254097  0.2354446  0.20714598 0.23398979

In [8]:
#Consecutive Variables
array6=np.arange(20,100)
print(array6)
array7=np.arange(20,100,3) #arange(a,b,c) among a to b, multiple numbers of c
print(array7)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [33]:
#Indexing & slicing #
array1=np.array([2,3,5,7,11,13,17,19,23,31,37,41])
print(array1.size)
print(array1.shape)
print(type(array1))
print(array1[0:10:3])   # [a:b:c] : from a to b, c만큼 건너뛴 숫자 가져오기
array2=np.array([2,8,5]) #다른 array로 인덱싱하기. array1의 2,8,5번째 숫자 가져오기.
print(array1[array2])

12
(12,)
<class 'numpy.ndarray'>
[ 2  7 17 31]
[ 5 23 13]


In [70]:
#Boolean 연산
booleans=np.array(array1>10)
print(booleans)
print(array1)
print(np.where(booleans))  #TRUE인 값들만 불러옴
print(np.where(array1>5))  #booleans에서 2이상인 인덱스 값만 불러옴
filter=np.where(array1>5)  # 필터로 쓰기
print(array1[filter])

[False False False False  True  True  True  True  True  True  True  True]
[ 2  3  5  7 11 13 17 19 23 31 37 41]
(array([ 4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),)
(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),)
[ 7 11 13 17 19 23 31 37 41]


In [75]:
#Statistic in Nunpy
print(array1)
print(array1.mean())
print(np.median(array1))
print(array1.std())
print(array1.var())
print(array1.max())
print(array1.min())

[ 2  3  5  7 11 13 17 19 23 31 37 41]
17.416666666666668
15.0
12.671873929647852
160.57638888888889
41
2


## Numpy 배열 생성하기

In [ ]:
'''
Numpy는 Numeric Python의 약자이다..
수학분야 관련된 통계작업 시 python의 가장 기본이 되는 라이브러리
과학계산컴퓨팅 작업과 데이터 분석에 필요한 작업이 가능
리스트와 거의 흡사하지만 훨씬 빠르고 메모리 효율성이 높아서 성능상 우위.

1) import numpy
2) array(), random.random() 등 사용
'''

### 리스트와 numpy 배열 생성하고 비교

In [9]:
import numpy as np
# 1. Array 생성
mylist=list([[1,2,3],[4,5,6],[14,25,36]])
mynp=np.array(mylist)

print(mylist)
print(mynp)

'''
1. 리스트는 출력 결과가 []안에서 ","로 구분되는 반면, 
   ndarray는 []안에서 ","로 구분되지 않는다

2. numpy는 ndarray객체 타입으로 나온다.
   ndarray객체는 다차원 행렬 구조를 지원하는 Numpy의 핵심 클래스

3. 
'''


[[1, 2, 3], [4, 5, 6], [14, 25, 36]]
[[ 1  2  3]
 [ 4  5  6]
 [14 25 36]]


In [24]:
myListSub=mylist[0][0:2]
print(myListSub)
myListSub[0]=-5
myArraySub=mynp[0][0:2]
print(myArraySub)
myArraySub[0]=-5
print(myArraySub)

print(mylist)
print(mynp)

'''
numpy는 list와 거의 비슷하지만 list는 원본을 유지(메모리에서 다른 객체를 생성)하는 반면,
numpy는 원본을 바꿔 버림 >> 메모리 효율성 우수
'''

[1, 2]
[-5  2]
[-5  2]
[[1, 2, 3], [4, 5, 6], [14, 25, 36]]
[[-5  2  3]
 [ 4  5  6]
 [14 25 36]]


In [50]:
# 2.랜덤함수 사용해서 생성...
# rand(),randint()
a=np.random.rand(5,4)
print(a)
type(a)

b=np.random.randint(0,11,10)
print(b)

c=np.random.randn(10)
print(c)


[[0.35245982 0.03999816 0.3555122  0.27984581]
 [0.0958608  0.65335655 0.90633499 0.71254714]
 [0.96954332 0.08937245 0.9580215  0.07655861]
 [0.22260664 0.1721938  0.12497826 0.49229245]
 [0.20985367 0.59413495 0.56230438 0.50336611]]
[7 4 9 1 5 9 2 8 6 0]
[ 1.43579678  0.31883236 -1.52593747 -1.71780877  0.90363507  0.04396108
  0.73711415 -0.77340024  0.00347738 -0.9364474 ]


In [95]:
## 리스트와의 차이점
'''
np배열은 하나의 자료형만 저장 가능
즉, 숫자와 문자를 동시에 저장할 수 없다.
만약에 숫자와 문자가 동시에 저장되면 더 범용성 넓은 데이터 타입으로 모두 변환됨
이러한 제약 조건은 내부 원소에 대한 접근과 반복문 실행을 빨리하기 위함.
값의 타입을 dtype으로 명시 가능 int32/int64,float32/float64
type은 객체의 타입을 돌려줌. dtype은 요소의 타입
'''
L=[1,2,3,"4",5,6,7]#문자열 포함
L=[1,2,3,4.0,5,6,7]#실수 포함
npL=np.array(L)
npL # 데이터 타입이 다르면 더 범용성 넓은 데이터 타입으로 모두 적용

# 또는 dtype으로 지정
narr=np.array([1.2,3.4,37,0] , dtype="int32")
narr

array([ 1,  3, 37,  0])

## 배열 초기화

In [87]:
# 1. 0값으로 초기화
a=np.zeros(10)
print(a)

# 2. 3값으로 초기화
a=np.ones(10)+2
print(a)

# 4. 단위행렬(e)
a=np.eye(4)
print(a*a,"\n",a+a)

# 5. arange()
print(np.arange(5,20+1,4))

# 6. full(shape,)
a=np.full((5,5),-1.1,dtype="int32")
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 [[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
[ 5  9 13 17]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


## Numpy 배열의 속성과 기본함수
### ndim, shape(행X열),reshape, size, dtype, type

In [124]:
arr1=np.array([[1.0, 2,3],[4,5,6]], dtype="int32")
print(arr1)
print(type(arr1))
print(np.ndim(arr1))
print(np.shape(arr1))
print(np.size(arr1))
print("*"*60)

# 배열 요소값 type을 한번에 바꿀 때 사용
arr1.astype(np.float64)
arr2=np.arange(0,32).reshape(2,16)
print(arr2)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
6
************************************************************
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]]


## 랜덤함수와 seed값 설정하기

In [ ]:
'''
numpy random모듈(서브 패키지)에는 난수를 생성하는 다양한 함수들이 존재
그 중에서 가장 많이 사용되는 3가지... 
1) rand : 0 ~ 1사이의 실수값을 반환 - rand(행,열) 행X열 지정
2) randn : 가우시안 정규분포값 지정
3) randint : randint(row,high,size)
'''

In [14]:
np.random.seed(404)
print("*"*40,"np.random.randn(4,5)","*"*20)
print(np.random.randn(4,5))
print("*"*40,"np.random.rand(4,5)","*"*20)
print(np.random.rand(4,5))
print("*"*40,"np.random.randint(1,5,12).reshape(4,3)","*"*20)
print(np.random.randint(1,5,12).reshape(4,3))

**************************************** np.random.randn(4,5) ********************
[[-1.18269089  1.33746165 -0.31430504  0.5566431  -0.20929933]
 [-0.01180037  1.23493345 -0.04341894 -0.68178724  1.20069197]
 [ 1.34394438 -0.834109    1.0359977   1.6657991   0.94947856]
 [ 1.06700952  0.39448078  0.60035462 -1.35330447 -0.96449618]]
**************************************** np.random.rand(4,5) ********************
[[0.02537018 0.1601208  0.81913225 0.1515311  0.72590137]
 [0.00982155 0.70143236 0.22931261 0.98901718 0.58154452]
 [0.75553604 0.03819143 0.24365719 0.12186642 0.52535204]
 [0.97041149 0.0633353  0.35950761 0.2922847  0.9058014 ]]
**************************************** np.random.randint(1,5,12).reshape(4,3) ********************
[[2 2 4]
 [2 4 1]
 [2 3 2]
 [4 3 4]]
