## 인덱싱, 슬라이싱

In [3]:
import numpy as np

In [6]:
narray=np.arange(5)
narray

array([0, 1, 2, 3, 4])

In [21]:
print(narray[4]+narray[-1])
print(narray[:])
print(narray[-3:-1])

8
[0 1 2 3 4]
[2 3]


In [33]:
np.random.seed(100)
narray1=np.random.randint(0,20,16).reshape(4,4)
print(narray1)
print(narray1[1][2])

'''
인덱싱은  scala값 추출, 슬라이싱은 scala값과 벡터값 추출
2차원 배열에서의 인덱싱은 []안에 1개 인자를 슬라이싱 인덱스는 [,] 콤마를 기준으로 2개의 인자를 받는다.
앞의 인자값은 행의 index, 뒤의 인자값은 열의 index
,없이 :만 넣으면 모든 것을 다 포함한다.
'''

[[ 8  3  7 15]
 [16 10  2  2]
 [ 2 14  2 17]
 [16 15  4 11]]
2


'\n2차원 배열에서의 인덱싱, 슬라이싱 인덱스는 [,] 콤마를 기준으로 2개의 인자를 받는다.\n앞의 인자값은 행의 index, 뒤의 인자값은 열의 index\n,없이 :만 넣으면 모든 것을 다 포함한다.\n'

## 문제

In [38]:
# 1. narray에서 첫째줄 7을 가져오려면
print(narray1[0][2])
np.where(narray==7)

7


(array([], dtype=int64),)

In [45]:
# 2.두번째 라인 가져오기 
print(narray1[1,])
print(narray1[1,:])
print(narray1[1])
print(narray1[1][:])
print(narray1[1:2][:])# 2차원으로 출력

[16 10  2  2]
[16 10  2  2]
[16 10  2  2]
[[16 10  2  2]]
[16 10  2  2]


In [4]:
# 3. 전체 행에 대해서 4번째 열만 다 가져오려면
print(narray1[:,-1])
print(narray1[0:4,3:4])
print(narray1[:,2])

NameError: name 'narray1' is not defined

## 인덱싱과 조건 슬라이싱

In [23]:
np.random.seed(0)
narray3=np.random.randn(4,4)
print(narray3)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]]


In [6]:
print(narray3[narray3>0])
narray3[narray3<0]=0
narray3

[1.76405235 0.40015721 0.97873798 2.2408932  1.86755799 0.95008842
 0.4105985  0.14404357 1.45427351 0.76103773 0.12167502 0.44386323
 0.33367433]


array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [100]:
# 3. where
narray3_1=np.where(narray3>0,narray3,0)
narray3_1

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [115]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
bool_a=(a>2)
print(a[bool_a])# true인 값들만 출력 a[bool_a]

[3 4 5 6 7 8]


## 통계함수

In [130]:
np.random.seed(0)
arr4=np.random.randint(0,20,16).reshape(4,4)
arr4

array([[12, 15,  0,  3],
       [ 3,  7,  9, 19],
       [18,  4,  6, 12],
       [ 1,  6,  7, 14]])

In [46]:
'''
numpy 배열의 통계함수
sum(), mean(),min(),max(),argmin(),argmax(),cumsum()
'''
# axis=1: 같은 행에서 다른 열을 더하기
print(np.sum(arr4, axis=1))
# axis=1: 같은 열에서 다른 행을 더하기
print(np.sum(arr4, axis=0))
# axis 지정 X : 모든 요소 더하기
print(np.sum(arr4))
print("*"*50)
# cumsum : 누적합
print(np.cumsum(arr4,axis=1))
print("*"*50)
'''
axis=0
모든 행들을 다 검색
그중에서 가장 큰 값의 인덱스를 리턴
'''
print(np.argmax(arr4,axis=0))

NameError: name 'arr4' is not defined

In [44]:
np.random.seed(0)
narray=np.random.randn(2,8)
print(narray)
narray=narray.reshape(4,4)
print(narray)

[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
   0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351  0.76103773  0.12167502
   0.44386323  0.33367433]]
[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]]
